# Generated by Django 5.2.6 on 2025-09-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slot_hours',
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity_min',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='min_legit_attendees',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
