# Generated by Django 5.2.6 on 2025-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingwebsite', '0002_remove_room_slot_hours_alter_room_capacity_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('small', 'Small (1–3)'), ('normal', 'Normal (3–5)'), ('big', 'Big (5–8)')], max_length=10),
        ),
    ]
